---
name: Linting and code quality check

on: [push, pull_request]

jobs:
  lint:
    uses: mundialis/github-workflows/.github/workflows/linting.yml@main
    # with:
    #   # set pylint-version to empty string to skip the pylint workflow
    #   pylint-version: ''
    #   BASH_SEVERITY: 'warning'
    #   VALIDATE_DOCKERFILE_HADOLINT: false
    #   VALIDATE_JSON: false
    #   VALIDATE_HTML: false
    #   VALIDATE_CSS: false
    #   VALIDATE_BASH_EXEC: false

  post-pr-reviews:
    needs: lint
    if: ${{ needs.lint.result == 'failure' }}
    uses: mundialis/github-workflows/.github/workflows/post-pr-reviews.yml@add_post_pr_reviews
