---
name: Linting and code quality check

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    permissions:
      contents: read
      packages: read
      statuses: write
      pull-requests: write
    uses: mundialis/github-workflows/.github/workflows/linting.yml@main
