---
name: Upload Python Package

on:
  release:
    types: [published]

jobs:

  publish-python-test-pypi:
    uses: mundialis/github-workflows/.github/workflows/python-publish.yml@main
    with:
      test_pypi: true
    secrets:
      PYPI_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}

# uncomment for new plugins (not needed for example plugin)
  # publish-python-pypi:
  #   uses: mundialis/github-workflows/.github/workflows/python-publish.yml@main
  #   secrets:
  #     PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
